// Datos de pais/ciudad para el formulario de solicitud de acceso (MuroModal).
// Archivo de datos puro, sin tabla en Supabase: Mexico es el mercado real de
// Anfiora hoy, asi que trae su lista de ciudades; el resto del mundo solo
// trae el pais y la ciudad se captura como texto libre.

export interface Pais {
  nombre: string
  codigo: string
}

// Mexico primero porque es el default del selector.
export const PAISES: Pais[] = [
  { nombre: 'México', codigo: 'MX' },
  { nombre: 'Estados Unidos', codigo: 'US' },
  { nombre: 'España', codigo: 'ES' },
  { nombre: 'Colombia', codigo: 'CO' },
  { nombre: 'Argentina', codigo: 'AR' },
  { nombre: 'Chile', codigo: 'CL' },
  { nombre: 'Perú', codigo: 'PE' },
  { nombre: 'Ecuador', codigo: 'EC' },
  { nombre: 'Guatemala', codigo: 'GT' },
  { nombre: 'Costa Rica', codigo: 'CR' },
  { nombre: 'Panamá', codigo: 'PA' },
  { nombre: 'República Dominicana', codigo: 'DO' },
  { nombre: 'Puerto Rico', codigo: 'PR' },
  { nombre: 'Honduras', codigo: 'HN' },
  { nombre: 'El Salvador', codigo: 'SV' },
  { nombre: 'Nicaragua', codigo: 'NI' },
  { nombre: 'Venezuela', codigo: 'VE' },
  { nombre: 'Bolivia', codigo: 'BO' },
  { nombre: 'Paraguay', codigo: 'PY' },
  { nombre: 'Uruguay', codigo: 'UY' },
  { nombre: 'Brasil', codigo: 'BR' },
  { nombre: 'Canadá', codigo: 'CA' },
  { nombre: 'Otro', codigo: 'OTRO' },
]

export const CODIGO_PAIS_DEFAULT = 'MX'

export interface CiudadMexico {
  nombre: string
  estado: string
}

// Zonas metropolitanas completas, destinos de boda y playa, y las
// ciudades medianas de cada estado (lista de Diego, 283 entradas). Con
// estado para distinguir nombres repetidos (Guadalupe en NL y Zacatecas).
// Orden alfabetico por nombre, sin acentos.
export const CIUDADES_MEXICO: CiudadMexico[] = [
  { nombre: 'Acámbaro', estado: 'Guanajuato' },
  { nombre: 'Acapulco', estado: 'Guerrero' },
  { nombre: 'Actopan', estado: 'Hidalgo' },
  { nombre: 'Agua Prieta', estado: 'Sonora' },
  { nombre: 'Aguascalientes', estado: 'Aguascalientes' },
  { nombre: 'Ajijic', estado: 'Jalisco' },
  { nombre: 'Akumal', estado: 'Quintana Roo' },
  { nombre: 'Altamira', estado: 'Tamaulipas' },
  { nombre: 'Amealco', estado: 'Querétaro' },
  { nombre: 'Amecameca', estado: 'Estado de México' },
  { nombre: 'Apatzingán', estado: 'Michoacán' },
  { nombre: 'Apizaco', estado: 'Tlaxcala' },
  { nombre: 'Apodaca', estado: 'Nuevo León' },
  { nombre: 'Arriaga', estado: 'Chiapas' },
  { nombre: 'Atizapán de Zaragoza', estado: 'Estado de México' },
  { nombre: 'Atlixco', estado: 'Puebla' },
  { nombre: 'Autlán', estado: 'Jalisco' },
  { nombre: 'Bacalar', estado: 'Quintana Roo' },
  { nombre: 'Bahía de Banderas', estado: 'Nayarit' },
  { nombre: 'Bernal', estado: 'Querétaro' },
  { nombre: 'Boca del Río', estado: 'Veracruz' },
  { nombre: 'Cabo San Lucas', estado: 'Baja California Sur' },
  { nombre: 'Caborca', estado: 'Sonora' },
  { nombre: 'Cadereyta Jiménez', estado: 'Nuevo León' },
  { nombre: 'Calkiní', estado: 'Campeche' },
  { nombre: 'Calvillo', estado: 'Aguascalientes' },
  { nombre: 'Campeche', estado: 'Campeche' },
  { nombre: 'Cancún', estado: 'Quintana Roo' },
  { nombre: 'Cárdenas', estado: 'Tabasco' },
  { nombre: 'Catemaco', estado: 'Veracruz' },
  { nombre: 'Celaya', estado: 'Guanajuato' },
  { nombre: 'Celestún', estado: 'Yucatán' },
  { nombre: 'Chalco', estado: 'Estado de México' },
  { nombre: 'Champotón', estado: 'Campeche' },
  { nombre: 'Chapala', estado: 'Jalisco' },
  { nombre: 'Chetumal', estado: 'Quintana Roo' },
  { nombre: 'Chiapa de Corzo', estado: 'Chiapas' },
  { nombre: 'Chiautempan', estado: 'Tlaxcala' },
  { nombre: 'Chihuahua', estado: 'Chihuahua' },
  { nombre: 'Chilapa', estado: 'Guerrero' },
  { nombre: 'Chilpancingo', estado: 'Guerrero' },
  { nombre: 'Chimalhuacán', estado: 'Estado de México' },
  { nombre: 'Ciudad Acuña', estado: 'Coahuila' },
  { nombre: 'Ciudad Constitución', estado: 'Baja California Sur' },
  { nombre: 'Ciudad de México', estado: 'Ciudad de México' },
  { nombre: 'Ciudad del Carmen', estado: 'Campeche' },
  { nombre: 'Ciudad Guzmán', estado: 'Jalisco' },
  { nombre: 'Ciudad Hidalgo', estado: 'Michoacán' },
  { nombre: 'Ciudad Juárez', estado: 'Chihuahua' },
  { nombre: 'Ciudad Lerdo', estado: 'Durango' },
  { nombre: 'Ciudad Madero', estado: 'Tamaulipas' },
  { nombre: 'Ciudad Obregón', estado: 'Sonora' },
  { nombre: 'Ciudad Valles', estado: 'San Luis Potosí' },
  { nombre: 'Ciudad Victoria', estado: 'Tamaulipas' },
  { nombre: 'Coacalco', estado: 'Estado de México' },
  { nombre: 'Coatzacoalcos', estado: 'Veracruz' },
  { nombre: 'Colima', estado: 'Colima' },
  { nombre: 'Colotlán', estado: 'Jalisco' },
  { nombre: 'Comalcalco', estado: 'Tabasco' },
  { nombre: 'Comitán', estado: 'Chiapas' },
  { nombre: 'Comonfort', estado: 'Guanajuato' },
  { nombre: 'Compostela', estado: 'Nayarit' },
  { nombre: 'Córdoba', estado: 'Veracruz' },
  { nombre: 'Corregidora', estado: 'Querétaro' },
  { nombre: 'Coyoacán', estado: 'Ciudad de México' },
  { nombre: 'Cozumel', estado: 'Quintana Roo' },
  { nombre: 'Cuauhtémoc', estado: 'Chihuahua' },
  { nombre: 'Cuautitlán', estado: 'Estado de México' },
  { nombre: 'Cuautitlán Izcalli', estado: 'Estado de México' },
  { nombre: 'Cuautla', estado: 'Morelos' },
  { nombre: 'Cuernavaca', estado: 'Morelos' },
  { nombre: 'Culiacán', estado: 'Sinaloa' },
  { nombre: 'Cunduacán', estado: 'Tabasco' },
  { nombre: 'Delicias', estado: 'Chihuahua' },
  { nombre: 'Dolores Hidalgo', estado: 'Guanajuato' },
  { nombre: 'Durango', estado: 'Durango' },
  { nombre: 'Ecatepec', estado: 'Estado de México' },
  { nombre: 'El Fuerte', estado: 'Sinaloa' },
  { nombre: 'El Marqués', estado: 'Querétaro' },
  { nombre: 'El Salto', estado: 'Jalisco' },
  { nombre: 'Ensenada', estado: 'Baja California' },
  { nombre: 'Escuinapa', estado: 'Sinaloa' },
  { nombre: 'Fresnillo', estado: 'Zacatecas' },
  { nombre: 'García', estado: 'Nuevo León' },
  { nombre: 'General Escobedo', estado: 'Nuevo León' },
  { nombre: 'Gómez Palacio', estado: 'Durango' },
  { nombre: 'Guadalajara', estado: 'Jalisco' },
  { nombre: 'Guadalupe', estado: 'Nuevo León' },
  { nombre: 'Guadalupe', estado: 'Zacatecas' },
  { nombre: 'Guamúchil', estado: 'Sinaloa' },
  { nombre: 'Guanajuato', estado: 'Guanajuato' },
  { nombre: 'Guasave', estado: 'Sinaloa' },
  { nombre: 'Guaymas', estado: 'Sonora' },
  { nombre: 'Hermosillo', estado: 'Sonora' },
  { nombre: 'Hidalgo del Parral', estado: 'Chihuahua' },
  { nombre: 'Huamantla', estado: 'Tlaxcala' },
  { nombre: 'Huatulco', estado: 'Oaxaca' },
  { nombre: 'Huauchinango', estado: 'Puebla' },
  { nombre: 'Huejutla', estado: 'Hidalgo' },
  { nombre: 'Huichapan', estado: 'Hidalgo' },
  { nombre: 'Huixquilucan', estado: 'Estado de México' },
  { nombre: 'Iguala', estado: 'Guerrero' },
  { nombre: 'Irapuato', estado: 'Guanajuato' },
  { nombre: 'Isla Mujeres', estado: 'Quintana Roo' },
  { nombre: 'Ixmiquilpan', estado: 'Hidalgo' },
  { nombre: 'Ixtapa', estado: 'Guerrero' },
  { nombre: 'Ixtapaluca', estado: 'Estado de México' },
  { nombre: 'Ixtapan de la Sal', estado: 'Estado de México' },
  { nombre: 'Izamal', estado: 'Yucatán' },
  { nombre: 'Izúcar de Matamoros', estado: 'Puebla' },
  { nombre: 'Jerez', estado: 'Zacatecas' },
  { nombre: 'Jesús María', estado: 'Aguascalientes' },
  { nombre: 'Jiquilpan', estado: 'Michoacán' },
  { nombre: 'Jiutepec', estado: 'Morelos' },
  { nombre: 'Jojutla', estado: 'Morelos' },
  { nombre: 'Juchitán', estado: 'Oaxaca' },
  { nombre: 'Kanasín', estado: 'Yucatán' },
  { nombre: 'La Paz', estado: 'Baja California Sur' },
  { nombre: 'La Piedad', estado: 'Michoacán' },
  { nombre: 'Lagos de Moreno', estado: 'Jalisco' },
  { nombre: 'Lázaro Cárdenas', estado: 'Michoacán' },
  { nombre: 'León', estado: 'Guanajuato' },
  { nombre: 'Lerdo', estado: 'Durango' },
  { nombre: 'Lerma', estado: 'Estado de México' },
  { nombre: 'Linares', estado: 'Nuevo León' },
  { nombre: 'Loreto', estado: 'Baja California Sur' },
  { nombre: 'Los Cabos', estado: 'Baja California Sur' },
  { nombre: 'Los Mochis', estado: 'Sinaloa' },
  { nombre: 'Los Reyes La Paz', estado: 'Estado de México' },
  { nombre: 'Macuspana', estado: 'Tabasco' },
  { nombre: 'Malinalco', estado: 'Estado de México' },
  { nombre: 'Manzanillo', estado: 'Colima' },
  { nombre: 'Matamoros', estado: 'Tamaulipas' },
  { nombre: 'Matehuala', estado: 'San Luis Potosí' },
  { nombre: 'Mazamitla', estado: 'Jalisco' },
  { nombre: 'Mazatlán', estado: 'Sinaloa' },
  { nombre: 'Mérida', estado: 'Yucatán' },
  { nombre: 'Metepec', estado: 'Estado de México' },
  { nombre: 'Mexicali', estado: 'Baja California' },
  { nombre: 'Minatitlán', estado: 'Veracruz' },
  { nombre: 'Mineral del Monte', estado: 'Hidalgo' },
  { nombre: 'Mitla', estado: 'Oaxaca' },
  { nombre: 'Monclova', estado: 'Coahuila' },
  { nombre: 'Montemorelos', estado: 'Nuevo León' },
  { nombre: 'Monterrey', estado: 'Nuevo León' },
  { nombre: 'Morelia', estado: 'Michoacán' },
  { nombre: 'Moroleón', estado: 'Guanajuato' },
  { nombre: 'Motul', estado: 'Yucatán' },
  { nombre: 'Naucalpan', estado: 'Estado de México' },
  { nombre: 'Navojoa', estado: 'Sonora' },
  { nombre: 'Nezahualcóyotl', estado: 'Estado de México' },
  { nombre: 'Nicolás Romero', estado: 'Estado de México' },
  { nombre: 'Nogales', estado: 'Sonora' },
  { nombre: 'Nuevo Casas Grandes', estado: 'Chihuahua' },
  { nombre: 'Nuevo Laredo', estado: 'Tamaulipas' },
  { nombre: 'Nuevo Vallarta', estado: 'Nayarit' },
  { nombre: 'Oaxaca de Juárez', estado: 'Oaxaca' },
  { nombre: 'Ocosingo', estado: 'Chiapas' },
  { nombre: 'Ocotlán', estado: 'Jalisco' },
  { nombre: 'Ometepec', estado: 'Guerrero' },
  { nombre: 'Orizaba', estado: 'Veracruz' },
  { nombre: 'Pabellón de Arteaga', estado: 'Aguascalientes' },
  { nombre: 'Pachuca', estado: 'Hidalgo' },
  { nombre: 'Palenque', estado: 'Chiapas' },
  { nombre: 'Papantla', estado: 'Veracruz' },
  { nombre: 'Parras', estado: 'Coahuila' },
  { nombre: 'Pátzcuaro', estado: 'Michoacán' },
  { nombre: 'Pedro Escobedo', estado: 'Querétaro' },
  { nombre: 'Pénjamo', estado: 'Guanajuato' },
  { nombre: 'Petatlán', estado: 'Guerrero' },
  { nombre: 'Piedras Negras', estado: 'Coahuila' },
  { nombre: 'Pinotepa Nacional', estado: 'Oaxaca' },
  { nombre: 'Playa del Carmen', estado: 'Quintana Roo' },
  { nombre: 'Poza Rica', estado: 'Veracruz' },
  { nombre: 'Progreso', estado: 'Yucatán' },
  { nombre: 'Puebla', estado: 'Puebla' },
  { nombre: 'Puerto Escondido', estado: 'Oaxaca' },
  { nombre: 'Puerto Morelos', estado: 'Quintana Roo' },
  { nombre: 'Puerto Peñasco', estado: 'Sonora' },
  { nombre: 'Puerto Vallarta', estado: 'Jalisco' },
  { nombre: 'Querétaro', estado: 'Querétaro' },
  { nombre: 'Ramos Arizpe', estado: 'Coahuila' },
  { nombre: 'Reynosa', estado: 'Tamaulipas' },
  { nombre: 'Rincón de Romos', estado: 'Aguascalientes' },
  { nombre: 'Río Bravo', estado: 'Tamaulipas' },
  { nombre: 'Río Grande', estado: 'Zacatecas' },
  { nombre: 'Rioverde', estado: 'San Luis Potosí' },
  { nombre: 'Riviera Maya', estado: 'Quintana Roo' },
  { nombre: 'Rosarito', estado: 'Baja California' },
  { nombre: 'Sabinas', estado: 'Coahuila' },
  { nombre: 'Sabinas Hidalgo', estado: 'Nuevo León' },
  { nombre: 'Sahuayo', estado: 'Michoacán' },
  { nombre: 'Salamanca', estado: 'Guanajuato' },
  { nombre: 'Salina Cruz', estado: 'Oaxaca' },
  { nombre: 'Saltillo', estado: 'Coahuila' },
  { nombre: 'San Andrés Cholula', estado: 'Puebla' },
  { nombre: 'San Andrés Tuxtla', estado: 'Veracruz' },
  { nombre: 'San Blas', estado: 'Nayarit' },
  { nombre: 'San Carlos', estado: 'Sonora' },
  { nombre: 'San Cristóbal de las Casas', estado: 'Chiapas' },
  { nombre: 'San Felipe', estado: 'Baja California' },
  { nombre: 'San Francisco del Rincón', estado: 'Guanajuato' },
  { nombre: 'San José del Cabo', estado: 'Baja California Sur' },
  { nombre: 'San Juan de los Lagos', estado: 'Jalisco' },
  { nombre: 'San Juan del Río', estado: 'Querétaro' },
  { nombre: 'San Luis Potosí', estado: 'San Luis Potosí' },
  { nombre: 'San Martín Texmelucan', estado: 'Puebla' },
  { nombre: 'San Mateo Atenco', estado: 'Estado de México' },
  { nombre: 'San Miguel de Allende', estado: 'Guanajuato' },
  { nombre: 'San Nicolás de los Garza', estado: 'Nuevo León' },
  { nombre: 'San Pedro', estado: 'Coahuila' },
  { nombre: 'San Pedro Cholula', estado: 'Puebla' },
  { nombre: 'San Pedro Garza García', estado: 'Nuevo León' },
  { nombre: 'Santa Catarina', estado: 'Nuevo León' },
  { nombre: 'Santiago', estado: 'Nuevo León' },
  { nombre: 'Santiago Ixcuintla', estado: 'Nayarit' },
  { nombre: 'Sayulita', estado: 'Nayarit' },
  { nombre: 'Silao', estado: 'Guanajuato' },
  { nombre: 'Soledad de Graciano Sánchez', estado: 'San Luis Potosí' },
  { nombre: 'Sombrerete', estado: 'Zacatecas' },
  { nombre: 'Tacámbaro', estado: 'Michoacán' },
  { nombre: 'Tampico', estado: 'Tamaulipas' },
  { nombre: 'Tapachula', estado: 'Chiapas' },
  { nombre: 'Taxco', estado: 'Guerrero' },
  { nombre: 'Teapa', estado: 'Tabasco' },
  { nombre: 'Tecámac', estado: 'Estado de México' },
  { nombre: 'Tecate', estado: 'Baja California' },
  { nombre: 'Tecomán', estado: 'Colima' },
  { nombre: 'Tehuacán', estado: 'Puebla' },
  { nombre: 'Temixco', estado: 'Morelos' },
  { nombre: 'Tenancingo', estado: 'Estado de México' },
  { nombre: 'Teotihuacán', estado: 'Estado de México' },
  { nombre: 'Tepatitlán', estado: 'Jalisco' },
  { nombre: 'Tepic', estado: 'Nayarit' },
  { nombre: 'Tepoztlán', estado: 'Morelos' },
  { nombre: 'Tequila', estado: 'Jalisco' },
  { nombre: 'Tequisquiapan', estado: 'Querétaro' },
  { nombre: 'Texcoco', estado: 'Estado de México' },
  { nombre: 'Teziutlán', estado: 'Puebla' },
  { nombre: 'Tijuana', estado: 'Baja California' },
  { nombre: 'Tizayuca', estado: 'Hidalgo' },
  { nombre: 'Tizimín', estado: 'Yucatán' },
  { nombre: 'Tlajomulco de Zúñiga', estado: 'Jalisco' },
  { nombre: 'Tlalnepantla', estado: 'Estado de México' },
  { nombre: 'Tlapa', estado: 'Guerrero' },
  { nombre: 'Tlaquepaque', estado: 'Jalisco' },
  { nombre: 'Tlaxcala', estado: 'Tlaxcala' },
  { nombre: 'Tlaxiaco', estado: 'Oaxaca' },
  { nombre: 'Todos Santos', estado: 'Baja California Sur' },
  { nombre: 'Toluca', estado: 'Estado de México' },
  { nombre: 'Tonalá', estado: 'Jalisco' },
  { nombre: 'Torreón', estado: 'Coahuila' },
  { nombre: 'Tula de Allende', estado: 'Hidalgo' },
  { nombre: 'Tulancingo', estado: 'Hidalgo' },
  { nombre: 'Tultitlán', estado: 'Estado de México' },
  { nombre: 'Tulum', estado: 'Quintana Roo' },
  { nombre: 'Tuxpan', estado: 'Veracruz' },
  { nombre: 'Tuxtepec', estado: 'Oaxaca' },
  { nombre: 'Tuxtla Gutiérrez', estado: 'Chiapas' },
  { nombre: 'Umán', estado: 'Yucatán' },
  { nombre: 'Uriangato', estado: 'Guanajuato' },
  { nombre: 'Uruapan', estado: 'Michoacán' },
  { nombre: 'Valladolid', estado: 'Yucatán' },
  { nombre: 'Valle de Bravo', estado: 'Estado de México' },
  { nombre: 'Valle de Santiago', estado: 'Guanajuato' },
  { nombre: 'Veracruz', estado: 'Veracruz' },
  { nombre: 'Villa de Álvarez', estado: 'Colima' },
  { nombre: 'Villahermosa', estado: 'Tabasco' },
  { nombre: 'Xalapa', estado: 'Veracruz' },
  { nombre: 'Xalisco', estado: 'Nayarit' },
  { nombre: 'Xochimilco', estado: 'Ciudad de México' },
  { nombre: 'Xochitepec', estado: 'Morelos' },
  { nombre: 'Yautepec', estado: 'Morelos' },
  { nombre: 'Yuriria', estado: 'Guanajuato' },
  { nombre: 'Zacatecas', estado: 'Zacatecas' },
  { nombre: 'Zacatelco', estado: 'Tlaxcala' },
  { nombre: 'Zacatlán', estado: 'Puebla' },
  { nombre: 'Zamora', estado: 'Michoacán' },
  { nombre: 'Zapopan', estado: 'Jalisco' },
  { nombre: 'Zihuatanejo', estado: 'Guerrero' },
  { nombre: 'Zinacantepec', estado: 'Estado de México' },
  { nombre: 'Zitácuaro', estado: 'Michoacán' },
  { nombre: 'Zumpango', estado: 'Estado de México' },
]

export function nombrePais(codigo: string): string {
  return PAISES.find(p => p.codigo === codigo)?.nombre ?? codigo
}
